import AutoDiff as ad

if __name__ == '__main__':
    a = ad.array(2)
    print(a.value)
    print(a.shape)
    print(a.check_shape())
    print(a.shape[-1])
    print()

    a = ad.array(2, outer_shape=(1, ))
    print(a.value)
    print(a.shape)
    print(a.check_shape())
    print(a.shape[-1])
    print()

    a = ad.array(3, outer_shape=(2, 3))
    print(a.value)
    print(a.shape)
    print(a.check_shape())
    print(a.shape[-1])
    print()

    a = ad.array(a, outer_shape=(3, 2))
    print(a.value)
    print(a.shape)
    print(a.check_shape())
    print(a.shape[-1])
    print()

    a = ad.array([3], outer_shape=(2,))
    print(a.value)
    print(a.shape)
    print(a.check_shape())
    print(a.shape[-1])
    print()

    a = ad.array([[3, 2], [3, 2]], outer_shape=(2,))
    print(a.value)
    print(a.shape)
    print(a.check_shape())
    print(a.shape[-1])
    print()

    # a = ad.tensor([[3, 2]])
    a = ad.array([3, 2])
    print(a.value)
    print(a.shape)
    print(a.check_shape())
    print(a.shape[-1])
    print()

    a = ad.array(ad.tensor(a))
    print(a.value)
    print(a.shape)
    print(a.check_shape())
    print(a.shape[-1])
    print()

    a = ad.array(ad.tensor(a))
    print(a.value)
    print(a.shape)
    print(a.check_shape())
    print(a.shape[-1])
    print()
    a = ad.array(a)
    print(a.value)
    print(a.shape)
    print(a.check_shape())
    print(a.shape[-1])
    print()
    a = ad.array(a, outer_shape=(2, 1))
    print(a.value)
    print(a.shape)
    print(a.check_shape())
    print(a.shape[-1])
    print()

